[project]
name = "wikiart-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asyncio>=4.0.0",
    "loguru>=0.7.3",
    "playwright>=1.55.0",
    "pydantic>=2.12.3",
    "typing>=3.10.0.0",
]
